ALTER TABLE "incidents" DROP CONSTRAINT "incidents_needs_array_check";--> statement-breakpoint
ALTER TABLE "incidents" DROP CONSTRAINT "incidents_risk_flags_object_check";--> statement-breakpoint
ALTER TABLE "incidents" DROP CONSTRAINT "incidents_unknowns_array_check";--> statement-breakpoint
ALTER TABLE "organizations" DROP CONSTRAINT "organizations_sectors_array_check";--> statement-breakpoint
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_incident_type_check" CHECK ("incidents"."incident_type" is null or "incidents"."incident_type" in ('flood', 'landslide', 'cyclone', 'fire', 'earthquake', 'displacement', 'food_insecurity', 'water_shortage', 'medical_access', 'other'));--> statement-breakpoint
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_country_check" CHECK ("incidents"."country" = 'Bangladesh');--> statement-breakpoint
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_division_check" CHECK ("incidents"."division" = 'Chattogram');--> statement-breakpoint
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_district_check" CHECK ("incidents"."district" is null or "incidents"."district" in ('Cox''s Bazar', 'Chattogram', 'Bandarban', 'Rangamati', 'Khagrachhari', 'Feni', 'Noakhali', 'Lakshmipur', 'Cumilla', 'Chandpur', 'Brahmanbaria', 'Other or Unknown'));--> statement-breakpoint
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_needs_array_check" CHECK (jsonb_typeof("incidents"."needs") = 'array' and "incidents"."needs" <@ '["rescue","shelter","food","water","medical","sanitation","protection","transport","information","other"]'::jsonb and jsonb_array_length("incidents"."needs") <= 10);--> statement-breakpoint
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_risk_flags_object_check" CHECK (jsonb_typeof("incidents"."risk_flags") = 'object' and "incidents"."risk_flags" ?& array['peopleTrapped', 'noSafeWater', 'noFood', 'urgentMedicalNeed', 'displacement', 'vulnerableGroupsReported', 'accessBlocked'] and "incidents"."risk_flags" - array['peopleTrapped', 'noSafeWater', 'noFood', 'urgentMedicalNeed', 'displacement', 'vulnerableGroupsReported', 'accessBlocked'] = '{}'::jsonb and jsonb_typeof("incidents"."risk_flags"->'peopleTrapped') = 'boolean' and jsonb_typeof("incidents"."risk_flags"->'noSafeWater') = 'boolean' and jsonb_typeof("incidents"."risk_flags"->'noFood') = 'boolean' and jsonb_typeof("incidents"."risk_flags"->'urgentMedicalNeed') = 'boolean' and jsonb_typeof("incidents"."risk_flags"->'displacement') = 'boolean' and jsonb_typeof("incidents"."risk_flags"->'vulnerableGroupsReported') = 'boolean' and jsonb_typeof("incidents"."risk_flags"->'accessBlocked') = 'boolean');--> statement-breakpoint
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_unknowns_array_check" CHECK (jsonb_typeof("incidents"."unknowns") = 'array' and jsonb_array_length("incidents"."unknowns") <= 10 and not jsonb_path_exists("incidents"."unknowns", '$[*] ? (@.type() != "string")'));--> statement-breakpoint
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_sectors_array_check" CHECK (jsonb_typeof("organizations"."sectors") = 'array' and "organizations"."sectors" <@ '["search_and_rescue","emergency_response","shelter","camp_management","food_assistance","nutrition","water_sanitation_hygiene","health","emergency_medical_support","protection","logistics","emergency_transport","information_management","community_communication","other"]'::jsonb);